/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e6e1e1",
        "inverse-primary": "#83d8a0",
        "on-primary-fixed": "#00210f",
        "on-secondary-fixed": "#1d1c12",
        "on-primary-container": "#93e9af",
        "surface-tint": "#0c6c3e",
        "on-surface-variant": "#3f4941",
        "secondary-fixed": "#e8e2d2",
        "primary-container": "#086b3d",
        "tertiary": "#8c0046",
        "tertiary-fixed-dim": "#ffb1c6",
        "outline": "#6f7a70",
        "accent-yellow": "#FFD600",
        "on-secondary-container": "#666356",
        "tertiary-fixed": "#ffd9e1",
        "primary-fixed": "#9ff5ba",
        "inverse-on-surface": "#f4f0ef",
        "on-secondary-fixed-variant": "#49473b",
        "error": "#ba1a1a",
        "on-background": "#1c1b1b",
        "outline-variant": "#bec9be",
        "on-error": "#ffffff",
        "secondary-container": "#e5dfcf",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#3f001c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffc8d5",
        "surface-container": "#f1edec",
        "secondary": "#625e51",
        "primary-fixed-dim": "#83d8a0",
        "on-surface": "#1c1b1b",
        "surface-container-highest": "#e6e1e1",
        "surface-bright": "#fdf8f8",
        "on-error-container": "#93000a",
        "surface-dim": "#ddd9d8",
        "surface-container-low": "#f7f2f2",
        "secondary-fixed-dim": "#cbc6b6",
        "on-secondary": "#ffffff",
        "primary": "#00512c",
        "error-container": "#ffdad6",
        "surface-container-high": "#ece7e7",
        "inverse-surface": "#313030",
        "paper-shadow": "#E6DEC5",
        "background": "#fdf8f8",
        "on-primary-fixed-variant": "#00522d",
        "surface-container-lowest": "#ffffff",
        "terminal-deep": "#042B19",
        "on-tertiary-fixed-variant": "#8e0047",
        "surface": "#fdf8f8",
        "tertiary-container": "#b7005e",
        "sea": "#0E5145",
        "sea-deep": "#0A3E35",
        "terracotta": "#C4572F",
        "cream": "#F6EEDC",
        "paper": "#FBF4E4",
        "sand": "#E5D6B4",
      },
      fontFamily: {
        "display-xl": ["Outfit", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "SF Mono", "monospace"],
        "meta-mono": ["JetBrains Mono", "ui-monospace", "SF Mono", "monospace"],
        "headline-lg": ["Outfit", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-bold": ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-serif": ["Cormorant Garamond", "Playfair Display", "Georgia", "serif"],
        "refined-sans": ["Raleway", "Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        "dm-sans": ["DM Sans", "Raleway", "Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "74px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "meta-mono": ["13px", { lineHeight: "20px", letterSpacing: "0.03em", fontWeight: "500" }],
        "headline-lg": ["44px", { lineHeight: "48px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["34px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-bold": ["16px", { lineHeight: "26px", fontWeight: "700" }],
      },
      spacing: {
        unit: "4px",
        "indent-asymmetric": "64px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        morph: {
          "0%, 100%": { borderRadius: "60% 40% 30% 70% / 60% 30% 70% 40%" },
          "50%": { borderRadius: "30% 60% 70% 40% / 50% 60% 30% 60%" },
        },
        fadeUp: {
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        morph: "morph 8s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
